#!/bin/bash -e
if [[ -z "${1}" ]]; then
	echo "Usage: ${0} [REPO]"
	exit 1
fi

prefix=$(dirname "${0}")
cd "${prefix}/${1}"

for pkgbase in `cat ../community.list`; do \
    mkdir -p "../../${pkgbase}"
    for file in `ls $pkgbase/trunk`; do
		echo "    ${file}"
		cp "${pkgbase}/trunk/${file}" "../../${pkgbase}"
		git add "../../${pkgbase}/${file}"
	done
	svn_log=$(svn log -l 1 "${pkgbase}/trunk"|head -n-1|tail -n-2)
	git commit -v "../../${pkgbase}" -m "$svn_log"
done

