#!/usr/bin/env bash
set -ex
if [[ -z "${1}" ]]; then
	echo "Usage: ${0} [REPO]"
	exit 1
fi

prefix=$(dirname "${0}")
pushd "${prefix}/${1}" &> /dev/null

for pkgbase in `cat ../community.list`; do \
    [ ! -d "${pkgbase}" ] && svn update "${pkgbase}"
    [ -d "../../${pkgbase}" ] && continue
    mkdir -p "../../${pkgbase}"
    for file in `ls $pkgbase/trunk`; do
		echo "    ${file}"
		cp "${pkgbase}/trunk/${file}" "../../${pkgbase}"
		git add "../../${pkgbase}/${file}"
	done
    pushd "$pkgbase/trunk" &> /dev/null
    makepkg --printsrcinfo > "../../../../${pkgbase}/.SRCINFO"
    git add "../../../../${pkgbase}/.SRCINFO"
    popd &> /dev/null
    svn_log=$(svn log -l 1 "${pkgbase}/trunk"|head -n-1|tail -n-2)
    git commit -v "../../${pkgbase}" -m "$svn_log" || true
done

