[__config__]
oldver = "old.txt"
newver = "new.txt"
keyfile = "apikeys.ini"

[acpid]
source = "git"
git = "git+https://git.code.sf.net/p/acpid2/code"
use_max_tag = true

[bolt]
source = "git"
git = "git+https://gitlab.freedesktop.org/bolt/bolt"
use_max_tag = true

[bucklespring]
source = "github"
github = "zevv/bucklespring"
prefix = "v"
use_max_tag = true

[containerd]
source = "github"
github = "containerd/containerd"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[darktable]
source = "github"
github = "darktable-org/darktable"
prefix = "release-"
use_max_tag = true
ignored = "release0.4 0.4 0.3 release-3.5.0 release-3.4.1.1"
exclude_regex = ".*(rc).*"

[delve]
source = "github"
github = "go-delve/delve"
prefix = "v"
use_max_tag = true

[docker-compose]
source = "github"
github = "docker/compose"
use_max_tag = true
prefix = "v"
exclude_regex = ".*(rc).*"

[font-awesome]
source = "github"
github = "FortAwesome/Font-Awesome"
use_max_tag = true

[fzf]
source = "github"
github = "junegunn/fzf"
use_max_tag = true
from_pattern = "(\\d+)\\.(\\d+)\\.(\\d+)\\-(\\d+)"
to_pattern = "\\1.\\2.\\3.\\4"

[git-lfs]
source = "github"
github = "git-lfs/git-lfs"
prefix = "v"
use_max_tag = true

[go]
source = "github"
github = "golang/go"
prefix = "go"
use_max_tag = true
exclude_regex = ".*(release|weekly|rc|alpha|beta).*"

[go-md2man]
source = "github"
github = "cpuguy83/go-md2man"
prefix = "v"
use_max_tag = true

[gopass]
source = "github"
github = "gopasspw/gopass"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(rc).*"

[hexedit]
source = "github"
github = "pixel/hexedit"
use_max_tag = true

[hy]
source = "github"
github = "hylang/hy"
use_max_tag = true
exclude_regex = ".*(a).*"

[i3-gaps]
source = "github"
github = "Airblader/i3"
use_max_tag = true

[influxdb]
source = "github"
github = "influxdata/influxdb"
prefix = "v"
use_max_tag = true
ignored = "v9.9.9"
exclude_regex = "v.*(rc|alpha|beta).*"

[jgmenu]
source = "github"
github = "johanmalm/jgmenu"
prefix = "v"
use_max_tag = true

[jp2a]
source = "github"
github = "Talinx/jp2a"
prefix = "v"
use_max_tag = true

[kakoune]
source = "github"
github = "mawww/kakoune"
prefix = "v"
use_latest_release = true

[lostfiles]
source = "github"
github = "graysky2/lostfiles"
prefix = "v"
use_max_tag = true

[mopidy]
source = "github"
github = "mopidy/mopidy"
prefix = "v"
use_max_tag = true
exclude_regex = "v\\d\\.\\d\\.\\d(a|b).*"

[mypy]
source = "pypi"
pypi = "mypy"

[neofetch]
source = "github"
github = "dylanaraps/neofetch"
use_max_tag = true

[pass-otp]
source = "github"
github = "tadfisher/pass-otp"
prefix = "v"
use_max_tag = true

[pdfjs]
source = "github"
github = "mozilla/pdf.js"
prefix = "v"
use_max_tag = true

[protege]
source = "github"
github = "protegeproject/protege"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(rc|alpha|beta).*"

[py3status]
source = "github"
github = "ultrabug/py3status"
use_max_tag = true

[python-argparse]
source = "pypi"
pypi = "argparse"

[python-pykka]
source = "pypi"
pypi = "pykka"

[python-autobahn]
source = "pypi"
pypi = "autobahn"

[python-babel]
source = "pypi"
pypi = "babel"
prefix = "v"

[python-docker]
source = "pypi"
pypi = "docker"

[python-docker-pycreds]
source = "pypi"
pypi = "docker-pycreds"

[python-dockerpty]
source = "pypi"
pypi = "dockerpty"

[python-docs]
source = "github"
github = "python/cpython"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(a|b|rc).*"

[python-hidapi]
source = "pypi"
pypi = "hidapi"
from_pattern = "(\\d+)\\.(\\d+)\\.(\\d+)\\.post(\\d+)"
to_pattern = "\\1.\\2.\\3.\\4"

[python-jsonrpclib-pelix]
source = "pypi"
pypi = "jsonrpclib-pelix"

[python-jsonrpc-server]
source = "pypi"
pypi = "python-jsonrpc-server"

[python-keyutils]
source = "pypi"
pypi = "keyutils"

[python-language-server]
source = "pypi"
pypi = "python-language-server"

[python-ldap]
source = "pypi"
pypi = "python-ldap"

[python-m2crypto]
source = "pypi"
pypi = "M2Crypto"

[python-mypy_extensions]
source = "pypi"
pypi = "mypy_extensions"

[python-pew]
source = "pypi"
pypi = "pew"

[python-pipenv]
source = "pypi"
pypi = "pipenv"

[python-psycopg2]
source = "pypi"
pypi = "psycopg2"

[python-pyaes]
source = "pypi"
pypi = "pyaes"

[python-pycountry]
source = "pypi"
pypi = "pycountry"

[python-pydocstyle]
source = "pypi"
pypi = "pydocstyle"

[python-pypeg2]
source = "pypi"
pypi = "pypeg2"

[python-pyserial]
source = "pypi"
pypi = "pyserial"

[python-pywal]
source = "pypi"
pypi = "pywal"

[python-rope]
source = "pypi"
pypi = "rope"

[python-send2trash]
source = "pypi"
pypi = "send2trash"

[python-shutilwhich]
source = "pypi"
pypi = "shutilwhich"

[python-sqlobject]
source = "pypi"
pypi = "sqlobject"

[python-sqlparse]
source = "pypi"
pypi = "sqlparse"

[python-wheel]
source = "pypi"
pypi = "wheel"

[python-wxpython]
source = "pypi"
pypi = "wxpython"
from_pattern = "(\\d+)\\.(\\d+)\\.(\\d+)\\.post(\\d+)"
to_pattern = "\\1.\\2.\\3.\\4"

[python-xlib]
source = "pypi"
pypi = "python-xlib"

[qutebrowser]
source = "github"
github = "qutebrowser/qutebrowser"
prefix = "v"
use_max_tag = true

[restic]
source = "github"
github = "restic/restic"
prefix = "v"
use_max_tag = true

[rofi]
source = "github"
github = "DaveDavenport/rofi"
use_max_tag = true

[runc]
source = "github"
github = "opencontainers/runc"
use_max_tag = true
prefix = "v"
from_pattern = "v(\\d+)\\.(\\d+)\\.(\\d+)\\-rc(\\d+)"
to_pattern = "\\1.\\2.\\3rc\\4"

[udiskie]
source = "github"
prefix = "v"
github = "coldfix/udiskie"
use_max_tag = true

[podman]
source = "github"
github = "containers/libpod"
use_max_tag = true
prefix = "v"
exclude_regex = ".*rc.$"

[catatonit]
source = "github"
github = "openSUSE/catatonit"
use_max_tag = true
prefix = "v"

[python-prompt_toolkit]
source = "pypi"
pypi = "prompt-toolkit"

[buildah]
source = "github"
github = "containers/buildah"
use_max_tag = true
prefix = "v"

[skopeo]
source = "github"
github = "containers/skopeo"
use_max_tag = true
prefix = "v"

[yubico-c]
source = "github"
github = "Yubico/yubico-c"
prefix = "libyubikey-"
use_max_tag = true
ignored = "0.3.0 libyubikey-0.3.0"

[yubico-c-client]
source = "github"
github = "Yubico/yubico-c-client"
prefix = "ykclient-"
use_max_tag = true
exclude_regex = ".*(pre|rc|alpha|beta).*"

[yubico-pam]
source = "github"
github = "Yubico/yubico-pam"
use_max_tag = true

[yubikey-manager]
source = "github"
github = "Yubico/yubikey-manager"
prefix = "yubikey-manager-"
use_max_tag = true
exclude_regex = ".*(a|b|rc).$"

[yubikey-personalization]
source = "github"
github = "Yubico/yubikey-personalization"
prefix = "v"
use_max_tag = true

[yubikey-manager-qt]
source = "github"
github = "Yubico/yubikey-manager-qt"
prefix = "yubikey-manager-qt-"
use_max_tag = true
ignored = "0.3.0"
exclude_regex = ".*rc.$"

[qcustomplot]
source = "regex"
regex = "tags/v([\\d.]+)?"
url = "https://gitlab.com/DerManu/QCustomPlot/-/tags"

[nvme-cli]
source = "git"
git = "git://github.com/linux-nvme/nvme-cli"
prefix = "v"
use_max_tag = true

[nano-syntax-highlighting]
source = "github"
github = "scopatz/nanorc"
use_max_tag = true

[python-nltk]
source = "github"
github = "nltk/nltk"
use_max_tag = true
exclude_regex = ".*(b).*"

[python2-typing]
source = "github"
github = "python/typing"
use_max_tag = true

[archlinux-contrib]
source = "github"
github = "archlinux/contrib"
use_max_tag = true

[archlinux-repro]
source = "github"
github = "archlinux/archlinux-repro"
use_max_tag = true

[nageru]
source = "git"
git = "http://git.sesse.net/nageru"
use_max_tag = true

[bmusb]
source = "git"
git = "http://git.sesse.net/bmusb"
use_max_tag = true

[dqlite]
source = "github"
github = "canonical/dqlite"
prefix = "v"
use_max_tag = true

[lxd]
source = "github"
github = "lxc/lxd"
prefix = "lxd-"
use_max_tag = true

[raft]
source = "github"
github = "canonical/raft"
prefix = "v"
use_max_tag = true

[crun]
source = "github"
github = "containers/crun"
use_max_tag = true

[k9s]
source = "github"
github = "derailed/k9s"
prefix = "v"
use_max_tag = true

[python-typed-ast]
source = "github"
github = "python/typed_ast"
use_max_tag = true

[vim-ultisnips]
source = "github"
github = "SirVer/ultisnips"
use_max_tag = true

[conmon]
source = "github"
github = "containers/conmon"
prefix = "v"
use_max_tag = true

[slirp4netns]
source = "github"
github = "rootless-containers/slirp4netns"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(beta).*"

[toolbox]
source = "github"
github = "containers/toolbox"
prefix = "v"
use_max_tag = true

[cni-plugins]
source = "github"
github = "containernetworking/plugins"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[libslirp]
source = "git"
git = "git+https://gitlab.freedesktop.org/slirp/libslirp.git"
prefix = "v"
use_max_tag = true

[helm]
source = "github"
github = "helm/helm"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(rc).*"

[fuse-overlayfs]
source = "github"
github = "containers/fuse-overlayfs"
prefix = "v"
use_max_tag = true

[staticcheck]
source = "github"
github = "dominikh/go-tools"
use_max_tag = true

[rclone]
source = "github"
github = "rclone/rclone"
prefix = "v"
use_max_tag = true

[v2ray]
source = "github"
github = "v2fly/v2ray-core"
prefix = "v"
use_max_tag = true

[glider]
source = "github"
github = "nadoo/glider"
prefix = "v"
use_max_tag = true

[dns-over-https]
source = "github"
github = "m13253/dns-over-https"
prefix = "v"
use_max_tag = true

[barrier]
source = "github"
github = "debauchee/barrier"
prefix = "v"
use_max_tag = true

[screenkey]
source = "git"
git = "git+https://gitlab.com/screenkey/screenkey"
prefix = "v"
use_max_tag = true

[python-dotenv]
source = "github"
github = "theskumar/python-dotenv"
prefix = "v"
use_max_tag = true

[todoman]
source = "github"
github = "pimutils/todoman"
prefix = "v"
use_max_tag = true

[python-flask-babel]
source = "pypi"
pypi = "Flask-Babel"

[python-guzzle-sphinx-theme]
source = "pypi"
pypi = "guzzle_sphinx_theme"

[python-nbxmpp]
source = "pypi"
pypi = "nbxmpp"

[python-pydbus]
source = "pypi"
pypi = "pydbus"

[python-pydrive]
source = "pypi"
pypi = "PyDrive"

[python-pygame]
source = "pypi"
pypi = "pygame"

[python-reportlab]
source = "pypi"
pypi = "reportlab"

[python-speaklater]
source = "pypi"
pypi = "speaklater"

[python-sphinx-autorun]
source = "pypi"
pypi = "sphinx-autorun"

[github-cli]
source = "github"
github = "cli/cli"
prefix = "v"
exclude_regex = ".*(pre).*"
use_max_tag = true

[jq]
source = "github"
github = "stedolan/jq"
prefix = "jq-"
use_max_tag = true
exclude_regex = ".*(rc).*"

[zsh-completions]
source = "github"
github = "zsh-users/zsh-completions"
use_max_tag = true

[zsh-syntax-highlighting]
source = "github"
github = "zsh-users/zsh-syntax-highlighting"
use_max_tag = true
exclude_regex = ".*(alpha|beta).*"

[gopls]
source = "github"
github = "golang/tools"
prefix = "gopls/v"
use_max_tag = true
include_regex = "gopls/v.*"
exclude_regex = ".*(pre).*"

[python-hjson]
source = "github"
github = "hjson/hjson-py"
prefix = "v"
use_max_tag = true

[qmk]
source = "github"
github = "qmk/qmk_cli"
prefix = "v"
use_max_tag = true

[python-irc]
source = "github"
github = "jaraco/irc"
prefix = "v"
use_max_tag = true

[libmd]
source = "git"
git = "git+https://git.hadrons.org/git/libmd.git"
use_max_tag = true

[signing-party]
source = "gitlab"
gitlab = "signing-party-team/signing-party"
host = "salsa.debian.org"
use_max_tag = true
prefix = "v"

[perl-data-perl]
source = "cpan"
cpan = "Data-Perl"

[perl-anyevent-i3]
source = "manual"
manual = "0.17"

[perl-type-tiny]
source = "cpan"
cpan = "Type-Tiny"

[perl-strictures]
source = "cpan"
cpan = "strictures"

[perl-gnupg-interface]
source = "cpan"
cpan = "GnuPG-Interface"

[perl-moox-handlesvia]
source = "cpan"
cpan = "MooX-HandlesVia"

[perl-sub-handlesvia]
source = "cpan"
cpan = "Sub-HandlesVia"

[perl-moox-late]
source = "cpan"
cpan = "MooX-late"

[python-milc]
source = "pypi"
pypi = "milc"

[plocate]
source = "git"
git = "http://git.sesse.net/plocate"
use_max_tag = true

[python-google-api-core]
source = "pypi"
pypi = "google-api-core"

[python-google-api-python-client]
source = "pypi"
pypi = "google-api-python-client"

[python-pandas]
source = "pypi"
pypi = "pandas"

[python-pandas-datareader]
source = "pypi"
pypi = "pandas-datareader"

[kubernetes]
source = "github"
github = "kubernetes/kubernetes"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(rc|alpha|beta).*"

[docker]
source = "github"
github = "moby/moby"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(rc|alpha|beta).*"

[python-adblock]
source = "github"
github = "ArniDagur/python-adblock"
use_max_tag = true

[tailscale]
source = "github"
github = "tailscale/tailscale"
prefix = "v"
use_max_tag = true

[minicom]
source = "gitlab"
gitlab = "minicom-team/minicom"
host = "salsa.debian.org"
use_max_tag = true
prefix = "v"

[go-tools]
source = "github"
github = "golang/tools"
prefix = "v"
use_max_tag = true

[python2-docs]
source = "github"
github = "python/cpython"
prefix = "v"
use_max_tag = true
exclude_regex = "(v)?3.*(rc|a|beta)?.*"

[cri-o]
source = "github"
github = "cri-o/cri-o"
prefix = "v"
use_max_tag = true

[step-ca]
source = "github"
github = "smallstep/certificates"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[step-cli]
source = "github"
github = "smallstep/cli"
prefix = "v"
use_max_tag = true
exclude_regex = ".*(pre|rc|alpha|beta).*"

[salt]
source = "github"
github = "saltstack/salt"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[micro]
source = "github"
github = "zyedidia/micro"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[b4]
source = "git"
git = "https://git.kernel.org/pub/scm/utils/b4/b4.git/"
prefix = "v"
use_max_tag = true

[poke]
source = "git"
git = "https://git.savannah.gnu.org/git/poke.git"
prefix = "releases/poke-"
use_max_tag = true
include_regex = "releases/.*"

[bash-bats]
source = "github"
github = "bats-core/bats-core"
prefix = "v"
use_max_tag = true
exclude_regex = "v.*(pre|rc|alpha|beta).*"

[sbctl]
source = "github"
github = "foxboron/sbctl"
use_max_tag = true

[borg]
source = "github"
github = "borgbackup/borg"
use_max_tag = true
exclude_regex = ".*(a|b|dev).*"

[podman-dnsname]
source = "github"
github = "containers/dnsname"
prefix = "v"
use_max_tag = true

[python-fido2]
source = "github"
github = "Yubico/python-fido2"
use_max_tag = true

[lxc]
source = "github"
github = "lxc/lxc"
prefix = "lxc-"
use_max_tag = true
ignored = "start"

[lxcfs]
source = "github"
github = "lxc/lxcfs"
prefix = "lxcfs-"
use_max_tag = true

[dunst]
source = "github"
github = "dunst-project/dunst"
prefix = "v"
use_max_tag = true

[python-dotty-dict]
source = "github"
github = "pawelzny/dotty_dict"
prefix = "v"
use_max_tag = true

[qprint]
source = "repology"
repology = "qprint"

[python-halo]
source = "pypi"
pypi = "halo"

[python-log_symbols]
source = "pypi"
pypi = "log-symbols"

[python-spinners]
source = "pypi"
pypi = "spinners"

[python-hid]
source = "github"
github = "apmorton/pyhidapi"
prefix = "v"
use_max_tag = true

[nomad]
source = "github"
github = "hashicorp/nomad"
prefix = "v"
use_max_tag = true

[nomad-driver-podman]
source = "github"
github = "hashicorp/nomad-driver-podman"
prefix = "v"
use_max_tag = true

[nomad-driver-containerd]
source = "github"
github = "Roblox/nomad-driver-containerd"
prefix = "v"
use_max_tag = true

[nomad-driver-nspawn]
source = "github"
github = "JanMa/nomad-driver-nspawn"
prefix = "v"
use_max_tag = true

[nomad-driver-lxc]
source = "github"
github = "hashicorp/nomad-driver-lxc"
prefix = "v"
use_max_tag = true
